- type: "nginx/upstream"
  name: "status"
  tag: "pod-1"
  loadPolicy: "append"
  config: |
    server pod-1.koolie.svc.cluster.local:80;

- type: "nginx/upstream"
  name: "status"
  tag: "pod-2"
  loadPolicy: "append"
  config: |
    server pod-2.koolie.svc.cluster.local:80;

- type: "nginx/server"
  name: "foo.example.com"
  loadPolicy: "unique"
  config: |
    listen 80 default_server;

    listen 443 default_server ssl;

    server_name foo.example.com;

    ssl_certificate /etc/nginx/secrets/wildcard-yellowdog-tech.crt;
    ssl_certificate_key /etc/nginx/secrets/wildcard-yellowdog-tech.key;

- type: "nginx/location"
  name: "404"
  server: "foo.example.com"
  matchModifier: ""
  locationMatch: "/"
  loadPolicy: "unique"
  config: |
    return 404 "Not found";

- type: "nginx/location"
  name: "status"
  server: "foo.example.com"
  matchModifier: ""
  locationMatch: "/status/"
  loadPolicy: "unique"
  config: |
    return 200 "OK";